repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.6
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_commit_msg: '[ci skip] [pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: []
    submodules: false
