name: cf-admin-migrations
channels:
  - conda-forge
dependencies:
  - requests
  - git
  - tqdm
  - pygithub
  - gitpython
  - ruamel.yaml
  - ruamel.yaml.jinja2
  - conda-smithy
  - conda-build
  - rattler-build-conda-compat
  - python =3.11
  - pip
  - setuptools
